include:
  - project: 'famedly/company/devops/templates/ci-cd'
    ref: docker-v1
    file:
      - '/docker.yml'
  - project: 'famedly/company/devops/templates/ci-cd'
    ref: rust-v1
    file:
      - '/rust.yml'

stages:
  - build
  - lint
  - test
  - ci
  - build_docker

default:
  image: node:latest
  tags:
    - famedly
    - docker
  cache:
    paths:
      - node_modules/
      - build/

build:
  # Npm install / npm run build this thing
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    when: always
    paths:
      - node_modules/
      - build/

lint:
  # Verify the linting
  stage: lint
  script:
    - npm run lint

test:
  # Run the tests
  stage: test
  script:
    - npm run test

.enable_ssh: &enable_ssh |-
  eval `ssh-agent -s`
  echo "$CI_SSH_PRIVATE_KEY" | ssh-add -
  mkdir -p ~/.ssh
  echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

# TODO: replace with extending templates/ci-cd#rust-v1
# blocked by https://gitlab.com/famedly/company/devops/templates/ci-cd/-/issues/5#note_628602767
.rust: &rust |-
  echo "https://${GIT_CRATE_INDEX_USER}:${GIT_CRATE_INDEX_PASS}@gitlab.com" >> ~/.git-credentials
  git config --global credential.helper store
  sudo apt-get update -yqq
  sudo apt-get -yqq install build-essential cmake libssl-dev pkg-config
  curl https://sh.rustup.rs -sSf | sh -s -- -y
  source $HOME/.cargo/env
  rustup install stable
  rustup component add rustfmt
  rustup component add clippy
  [[ -n "$KTRA_CARGO_TOKEN" ]] && (echo $KTRA_CARGO_TOKEN | cargo login --registry="famedly")

.dev-env: &dev-env |-
  git clone --recursive git@gitlab.com:famedly/ansible/environments/local.git
  cd local
  ansible-playbook -vv -i inventory/ci.yaml --connection=local --limit localhost playbooks/site.yml

e2e-test:
  image: deb10-docker.qcow2
  stage: ci
  tags:
    - famedly
    - libvirt
    - generic
  script:
    - *enable_ssh
    - *rust
    - *dev-env
    - cargo test -- --nocapture
