image: node:latest

stages:
  - build
  - lint
  - test
  - build_docker

cache:
  paths:
    - node_modules/
    - build/

build:
  # Npm install / npm run build this thing
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    when: always
    paths:
      - node_modules/
      - build/

lint:
  # Verify the linting
  stage: lint
  script:
    - npm run lint

test:
  # Run the tests
  stage: test
  script:
    - npm run test

docker-build-master:
  image: docker:latest
  stage: build_docker
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

docker-build:
  image: docker:latest
  stage: build_docker
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
