include:
  - project: 'famedly/company/devops/templates/ci-cd'
    ref: docker-v1
    file:
      - '/docker.yml'
  - project: 'famedly/company/devops/templates/ci-cd'
    ref: rust-v1
    file:
      - '/rust.yml'

stages:
  - build
  - lint
  - test
  - deploy
  - user-stories

default:
  image: node:latest
  tags:
    - famedly
    - docker

build:
  # Npm install / npm run build this thing
  stage: build
  script:
    - npm install
    - npm run build

lint:
  # Verify the linting
  stage: lint
  script:
    - npm install
    - npm run lint

test:
  # Run the tests
  stage: test
  script:
    - npm install
    - npm run test

docker-releases:
  extends: .docker_releases

docker-tags:
  extends: .docker_tags

docker-branches:
  extends: .docker_branches

# We need to run user-stories after docker so we can test with the uploaded image
user-stories:
  stage: user-stories
  variables:
    # TODO: should use `uia_proxy_docker_tag` instead, but that's not available yet
    ANSIBLE_EXTRA_VARS: "{\"uia_proxy_docker_ref\": \"registry.gitlab.com/famedly/company/backend/services/uia-proxy:$CI_COMMIT_REF_NAME\"}"
  trigger:
    project: famedly/company/user-stories
    strategy: depend
