[package]
name = "uia-proxy"
version = "0.1.0"
authors = ["Johannes Becker <j.becker@famedly.com>"]
edition = "2018"

[dev-dependencies]
famedly-e2e-testing = { version = "0.0.1", registry = "famedly" }
