logging:
  console: info

# Webserver config
webserver:
  # The host where the webserver should listen to
  host: localhost
  # The port where the webserver should listen to
  port: 9740

# username mapper config
usernameMapper:
  # In which mode to operate, can be "plain" or "hmac-sha256"
  mode: hmac-sha256
  # the pepper to hash the usernames with
  pepper: <random secret>
  # the database folder for levelup
  folder: ./usernamemap

# The homeserver config
homeserver:
  # Domain of the homeserver
  domain: famedly.de
  # The reachable, local, URL of the homeserver
  url: http://localhost:8008
  # The reachable, external URL of the homeserver. Only needed when not https://{domain}.
  base: https://matrix.myserver.net
  # token config for the login-tokens of the homeserver
  token:
    # The shared secret for those tokens
    secret: <random secret>
    # The algorithm used for those tokens
    algorithm: HS512


# If you don't use OpenID you can remove this section
openid:
  # The default OpenID provider to use when one wasn't specified
  default: foo
  # Configurations for identity providers.
  providers:
    foo:
      # The issuer URL of this OpenID provider. Used for autodiscovery.
      issuer: "https://login.provider.com"
      # The relying party identifier at the OpenID provider
      client_id: "uia"
      # The secret which authenticates this relying party at the OP
      client_secret: "lak4sjd34hfuwie84bzvou3eqp1384znv1"
      # The OpenID scope value. Determines what information the OP sends.
      scopes: "openid"
      # Whether to enable autodiscovery. It's recommended to enable it.
      autodiscover: false
      # The authorization endpoint where the end user performs auth
      authorization_endpoint: "https://login.provider.com/auth"
      # The token endpoint where an auth code is exchanged for a token
      token_endpoint: "https://login.provider.com/token"
      # The provider's user info endpoint
      userinfo_endpoint: "https://login.provider.com/userinfo"
      # The URL where the OP publishes its JWK set of signing keys
      jwks_uri: "https://login.provider.com/jwks"
      # The JWT claim which identifies the user. Defaults to "sub".
      subject_claim: "sub"
      # A map of JWT claims to their expected values.
      expected_claims:
        can_login: true
        organization_id: "my_organization"
# Example using autodiscovery
#   bar:
#     issuer: "https://accounts.barprovider.com"
#     client_id: "matrix"
#     client_secret: "ynx4fwq34ushjvr84omibh3rdc1384mai1"
#     scopes: "openid profile"
#     autodiscover: true
#     subject_claim: "preferred_username"
#     expected_claims:
#       is_polite: true



# Stage template config (optional)
# Stages set here can be re-used later on in the uia config
stages:
  password: # The key is at the same time the alias of the stage
    type: m.login.password # The type of this stage
    config: # The config for this stage. Depends on stage type
      # m.login.password configures password providers
      passwordproviders:
        # Use the ldap password provider
        ldap:
          # the URL ldap is reachable at
          url: ldap://localhost
          # the base DN of the ldap
          base: dc=localhost,dc=localdomain,
          # the DN of the search user to initially bind with
          bindDn: uid=search,ou=users,dc=localhost,dc=localdomain
          # the bind password of the seach user
          bindPassword: super secret
          # the attribute mapping of the ldap
          attributes:
            # the username for people to log in as
            uid: uid
            # the persistent ID to create the mxid hashes of
            persistentId: persistentId
            enabled: enabled
  # More stage templates could be defined here, if wanted

# UIA template config (optional)
# Templates here can be re-used later on in the uia config
templates:
  password_only: # The key is at the same time the alias of the template
    # the config for this UIA template
    stages:
      password: # you can re-use stage templates here
    flows:
      - stages:
        - m.login.password

# Here we configure the different UIA endpoints
uia:
  # Config for the /login endpoint
  login:
    # Rate limit configruation for this endpoint
    rateLimit:
      # if rate limiting is enabled
      enabled: true
      # the window in ms for the rate limiting to happen
      windowMs: 60000
      # how many maximum hits in that window are allowed
      max: 5
    # All the stages needed to complete to fullfill UIA
    stages:
      # Here we use a stage tempalte from above. Note that it is still an object.
      # If we were to define any properties on this object we'd override the above config
      password:
      # And here we define a new stage inline, without using the stage templates
      m.login.dummy:
        # and, just as an example (m.login.dummy doesn't take any config), here is a config option
        #foo: bar
    # And now here is the config for all the different flows possible
    flows:
      - stages:
        # First we want the user to fullfill the password flow
        - m.login.password
        # Next we want the user to fullfill the dummy flow
        - m.login.dummy
  # Config for the password changing endpoint
  password:
    # we use a template defined in the "templates" section here
    password_only:
  # Instead of defining the config for every single endpoint, we just
  # define a default and use that
  default:
    password_only:
#  deleteDevice:
#    password_only:
#  deleteDevices:
#    password_only:
#  uploadDeviceSigningKeys:
#    password_only:
