version = 0
commit_goodlist = []

[authorization."Agatha Lovelace <a.lovelace@famedly.com>"]
sign_commit = true
sign_tag = true
sign_archive = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 8C48 6981 4B0D 6CFB 3CD1  0F31 1F4E 40EB AB7A 7076
Comment: Agatha V. Lovelace <a.lovelace@famedly.com>

xjMEZLZxqRYJKwYBBAHaRw8BAQdAq2oySe2xZXmEBxBt+buGSQlqnKkxhHR64asG
Th9F98XCwBEEHxYKAIMFgmS2cakFiQPCZwADCwkHCRAfTkDrq3pwdkcUAAAAAAAe
ACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmdyQgdsLW3CRieqySq4z9FN
Ol5xpubcrEGOTS5MXqmq3gMVCggCmwECHgEWIQSMSGmBSw1s+zzRDzEfTkDrq3pw
dgAAnAABAMKwuB/SV7cH2gLQgam2tvlx/8kv2q4611ZSC1FXpEsYAP9DqaAAqXlW
OledumoXAFMGB9aqMjwUc27IrT5Av+DGBc0rQWdhdGhhIFYuIExvdmVsYWNlIDxh
LmxvdmVsYWNlQGZhbWVkbHkuY29tPsLAFAQTFgoAhgWCZLZxqQWJA8JnAAMLCQcJ
EB9OQOurenB2RxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9y
ZzbokG1x4pJZCxsP92NF8RRT/FSo80H/WePfX0O6B2VfAxUKCAKZAQKbAQIeARYh
BIxIaYFLDWz7PNEPMR9OQOurenB2AAA1SwD/ZCyMh1snfnzrU0NfG50za0r6zB9+
LEcd8qxAjbhu9ZMBANSoGvPWjneQTmtBziNa5NzUawA2U81M8+pHMPN7yMENzjME
ZLZxqRYJKwYBBAHaRw8BAQdAPeuFjd6mQsenQmy1/VwHsbGi4po7d1Z0SG/q8p4q
HHHCwMUEGBYKATcFgmS2cakFiQPCZwAJEB9OQOurenB2RxQAAAAAAB4AIHNhbHRA
bm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ5KgN8I0ymg5Wu9kzyJzxXTGuMJjk3T7
pFXZ6lakj609ApsCvqAEGRYKAG8FgmS2cakJEEmYha2VP3K2RxQAAAAAAB4AIHNh
bHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ2AbHpmO8yCajeszcLOnVVHnkblg
YhemH6AGxl3dmPSjFiEEwhKs85GSrcH2IpybSZiFrZU/crYAAAZYAPsETtvCvwkS
bfRHGD47eHGBES4GJ9kw6ZEFYXalYBr16QD9FSeGPmW+DUmx+QP1liZ0CFh3rT2l
RfrB+ZOihSNpUA8WIQSMSGmBSw1s+zzRDzEfTkDrq3pwdgAAOwoBAPzApLEWn8i0
UgY4VghjEizop6ZkKq5vcE1/YH3lulJzAQDZvv1/YrLbY1mcOJI/pEGHI68VlHFS
AB0vVZMEZ+k3BA==
=V030
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Emelie Graven <e.graven@famedly.com>"]
sign_commit = true
sign_tag = true
sign_archive = true
add_user = true
retire_user = true
audit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 3061 EE49 E60A BC7A 6FD2  C4A0 89A1 D21A DC4A D1D9
Comment: Emelie Graven <e.graven@famedly.com>

xjMEZLZxqhYJKwYBBAHaRw8BAQdAxu33+xjQsD4KweeNL3jMp2b8VtzhoRSlUr6b
/GN4dAPCwBEEHxYKAIMFgmS2caoFiQPCZwADCwkHCRCJodIa3ErR2UcUAAAAAAAe
ACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmemOOynTSphJTAn82h3QDTb
no05g4jmqMRHoEkfV1MScgMVCggCmwECHgEWIQQwYe5J5gq8em/SxKCJodIa3ErR
2QAAO2cBAJsBCbwtYa1GMt43pxFY+UaLnitr0or71LRtMZEyHWL2AQCZ+ueQ+bGR
B8LbRQxvmfHwKZX54STpVvwUGv6wTw2CDc0kRW1lbGllIEdyYXZlbiA8ZS5ncmF2
ZW5AZmFtZWRseS5jb20+wsAUBBMWCgCGBYJktnGqBYkDwmcAAwsJBwkQiaHSGtxK
0dlHFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3JnyZK4CaVw
fJ8hribxLicu8yHGMc9GkN+EtZNiadgeUDEDFQoIApkBApsBAh4BFiEEMGHuSeYK
vHpv0sSgiaHSGtxK0dkAAH/yAP9fuSUe33WQXXA/CpQNMlBXL42oKFteie3S+0S9
ienR+gEAxv5D4GTw5ce60bYORVlG/L1dmbGlykE3uCluZQZz6QXOMwRktnGqFgkr
BgEEAdpHDwEBB0AiKkjWViOTH+gjOzGU4de2qeQ2M9sutXi3YOw31/PlXsLAxQQY
FgoBNwWCZLZxqgWJA8JnAAkQiaHSGtxK0dlHFAAAAAAAHgAgc2FsdEBub3RhdGlv
bnMuc2VxdW9pYS1wZ3Aub3JnAI5Dg/XJTtgNG+mxfTZ6O6AdG8R2fLSW4Lj+BiWU
UgECmwK+oAQZFgoAbwWCZLZxqgkQ7z7ppaFCe/JHFAAAAAAAHgAgc2FsdEBub3Rh
dGlvbnMuc2VxdW9pYS1wZ3Aub3JnHwPIUjlUyqCFvaVmJrVZSOzlkPWpR7f+0vOD
61/0nycWIQQFbQWVab9qso8YvxjvPumloUJ78gAA3KoA+wdVxUfLpyYVKjUTNcP2
yUKOwBmzCFGhJb9peDCXF4teAP9oDI5jVoKqW6yfsQUJHfjH+CIHIzxJXWaVOXsK
94PxBhYhBDBh7knmCrx6b9LEoImh0hrcStHZAABF9gEA5FXF0JQgNgEKGG+ITuP4
baCsYEDk39hyYjKHtKETEzwA/3YtNpxt8NSg/4XfT0NBzpQqdEfFMnHPVce95Dyp
zI0K
=HPxe
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Emily Dietrich <e.dietrich@famedly.com>"]
sign_commit = true
sign_tag = true
sign_archive = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 9ACB AA92 60AA A2CD 11BF  CB06 3417 BD11 6386 1C83
Comment: Emily Dietrich <e.dietrich@famedly.com>

xjMEZLZxqhYJKwYBBAHaRw8BAQdAZPmQBqLhTjby23K6Q9oPrgxdb79T7+f0gsNQ
N1tkemLCwBEEHxYKAIMFgmS2caoFiQPCZwADCwkHCRA0F70RY4Ycg0cUAAAAAAAe
ACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmfMDKHHW6kqmA0mDppthr5e
HLhPMYMbybFA83shUzB1ygMVCggCmwECHgEWIQSay6qSYKqizRG/ywY0F70RY4Yc
gwAAyjoA/25zbVEIT8XzkMn5OJZn7gkifIUoaikbsTv+QLrR5f8LAP9xyLAEWR7Q
6sMs97rpOepDWdEdiNkRQUCboXVz6KMZCM0nRW1pbHkgRGlldHJpY2ggPGUuZGll
dHJpY2hAZmFtZWRseS5jb20+wsAUBBMWCgCGBYJktnGqBYkDwmcAAwsJBwkQNBe9
EWOGHINHFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3Jnc28Q
Y8KBl/UeuDcc81gu/FC2sJgtzUoqcZvSR2UY3bsDFQoIApkBApsBAh4BFiEEmsuq
kmCqos0Rv8sGNBe9EWOGHIMAANRLAQC0eCuRCkoVKIwe3441E2I76pzHD5Ql8p5V
UenT6MhOdQD/RKGA6P6j5AnTP/SCO1BW6wwoSARUdKMQcQ4m2itdfQnOMwRktnGq
FgkrBgEEAdpHDwEBB0B9qike80pktehe975wKGxdCz5dHWUQbdff37R/dn3KQ8LA
xQQYFgoBNwWCZLZxqgWJA8JnAAkQNBe9EWOGHINHFAAAAAAAHgAgc2FsdEBub3Rh
dGlvbnMuc2VxdW9pYS1wZ3Aub3JntuIkcQL+pDVL0UXg3fplt6kYu+9gYkNDRba4
pSkvteoCmwK+oAQZFgoAbwWCZLZxqgkQw+RDpsUgom1HFAAAAAAAHgAgc2FsdEBu
b3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3JnT7bDu75uY7/DCCCykeGUzLolrmsHve1T
DZBpVfkONeMWIQT3MLEmg+kxEkQCntLD5EOmxSCibQAAtPIBAMT3ys7I2zkT2prr
WXBIH+kMFvxnhijPq+jECY7Lw5LdAQDDMswDPcLNBS73HGDVOowehVgRbN9vD2FF
GngYAYUsCRYhBJrLqpJgqqLNEb/LBjQXvRFjhhyDAADI5gD/RalXaqPD/xRZ+2r0
AivJjsYQyHEJe+kOm3QSyTMsSggA/iEIX2bBYKRkVnRjbV6QRlQazqU9+/nxmVJO
iTRgmdcE
=sJyq
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Felix Dommes <f.dommes@famedly.com>"]
sign_commit = true
sign_tag = true
sign_archive = true
add_user = true
retire_user = true
audit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 2051 EF8C 7CCE 4A59 F3D4  62E8 E799 681F E970 5796
Comment: Felix Dommes <f.dommes@famedly.com>

xjMEZLZxqhYJKwYBBAHaRw8BAQdAXa8+uTfT5qorYzv5d/IOuiICyfv1nOUBPM3z
qHdTiOrCwBEEHxYKAIMFgmS2caoFiQPCZwADCwkHCRDnmWgf6XBXlkcUAAAAAAAe
ACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmdZTNFR5+0TKFHybqqa5apK
lk0O5fnpxZrMb2sW9h8b7QMVCggCmwECHgEWIQQgUe+MfM5KWfPUYujnmWgf6XBX
lgAAjlABAMtRgbrXTwAYGeCp05VO0NyXjiStC6A5IlA6Uha9UDq9AQD/72h97vRD
q28/TNPAWK0bzJAcn1DwzmSEbuV3RF/bAM0jRmVsaXggRG9tbWVzIDxmLmRvbW1l
c0BmYW1lZGx5LmNvbT7CwBQEExYKAIYFgmS2caoFiQPCZwADCwkHCRDnmWgf6XBX
lkcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmfCX03IqDsV
QTib6iuZqwZ7a4KERQBdXQmQgp4GyHhWiwMVCggCmQECmwECHgEWIQQgUe+MfM5K
WfPUYujnmWgf6XBXlgAAGxcA/3OwebvkTesnkVdNayPDORWlsUS1M7RW5oJNKFxS
nlcPAP0cNPoFYzq2dim99tk1Xm5AJjUx4ch/I0exm3uvllrNCM4zBGS2caoWCSsG
AQQB2kcPAQEHQLENBLMrE5q+/H0ZB4URA3kSFVoUm8gIuv2zSkjnGKZqwsDFBBgW
CgE3BYJktnGqBYkDwmcACRDnmWgf6XBXlkcUAAAAAAAeACBzYWx0QG5vdGF0aW9u
cy5zZXF1b2lhLXBncC5vcmeQNt48FbfK0xW0LKQaCsy28BKgmcJVLI4P47QVMhS4
HwKbAr6gBBkWCgBvBYJktnGqCRDMcIYHag5ojkcUAAAAAAAeACBzYWx0QG5vdGF0
aW9ucy5zZXF1b2lhLXBncC5vcmdUoUW4JY6Mo+R44BmlEEEEajHSMDeKL/SqFQBu
VuwGvhYhBHmqggscwA9nmnG+E8xwhgdqDmiOAAAiHwD/YmaMIX093pdNg8XrpJJL
6cKr+Wagkw/FQl4o4uxfW14A/3dnw/cX28V7jmhfXST2hAx/mNGM3vvX/laT8thm
4boCFiEEIFHvjHzOSlnz1GLo55loH+lwV5YAAP44AP96Dd6lxixDbX/vPuBY/BIp
O+jSWK6uXiK3ibJ3Sj1m7QEA7lj5ixMcKqAX44/j/EY1anmcZDSNmln30GmcwS5G
SgA=
=3MeG
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Hristo Kamenov <h.kamenov@famedly.com>"]
sign_commit = true
sign_tag = true
sign_archive = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: CC31 659B 2006 7636 D6A7  AABB CC5A D96A 3D24 5FB9
Comment: Hristo Kamenov <h.kamenov@famedly.com>

xjMEZUPlRxYJKwYBBAHaRw8BAQdA+QGNLpbqQGAtSLAHtOAC9vo9zsxjQZ+pEJ+P
wlB0d+vCwBEEHxYKAIMFgmVD5UcFiQPCZwADCwkHCRDMWtlqPSRfuUcUAAAAAAAe
ACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmfgEjrtjecCkK5QMBZ5d8Ro
GAVqlHqVILFMOfrp1lyjCAMVCggCmwECHgEWIQTMMWWbIAZ2NtanqrvMWtlqPSRf
uQAAJrUBAOtrX9dxhkaq7X4Tpk0+hji1iRlqTzXiGnu0Be5zJjn4AP4yjYaNbMQx
NYwyNMnC3f7ztKk8RB1axQ6BppiQvuEmBc0mSHJpc3RvIEthbWVub3YgPGgua2Ft
ZW5vdkBmYW1lZGx5LmNvbT7CwBQEExYKAIYFgmVD5UcFiQPCZwADCwkHCRDMWtlq
PSRfuUcUAAAAAAAeACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmeuCeHm
UiXUo30vVr9BXcmzjHkQMAZ8ZtqJhPKxey9FTAMVCggCmQECmwECHgEWIQTMMWWb
IAZ2NtanqrvMWtlqPSRfuQAAC0MBAMifUAPOYFdlBMzj+EUQ1/ni9hYbJNXMfkyL
VQNYfGBzAQCiW5igjt9vh8lS6IsHVXVhCcUQ5WFY+87gG8sEAuAPCM4zBGVD5UcW
CSsGAQQB2kcPAQEHQD8o2a6MfxjFri/QzROnQ+IFH3T334Xc7ZT4nP8doIUUwsDF
BBgWCgE3BYJlQ+VHBYkDwmcACRDMWtlqPSRfuUcUAAAAAAAeACBzYWx0QG5vdGF0
aW9ucy5zZXF1b2lhLXBncC5vcmcnbN//oLBZ39JAecRZEKTO6SUHDFpheNta32tm
N15whAKbAr6gBBkWCgBvBYJlQ+VHCRCbnIRHAE5UokcUAAAAAAAeACBzYWx0QG5v
dGF0aW9ucy5zZXF1b2lhLXBncC5vcmdnUZI5+QOeVxwjS5XIyKAQBz0HNJOpmvJc
Ay5QqfOe6BYhBKMvL2hGKTKtojF8wpuchEcATlSiAAD16AD/eTtav3haWiv1P0/w
0MgTD/knUfV0iZ6Io0XfmuroUxsA/RQnUgdZrR4iMsOIBQOnopmiKocnLZM2aveR
lbe3mrcKFiEEzDFlmyAGdjbWp6q7zFrZaj0kX7kAAFLHAQCQprfah4AQPKVS48qU
QRTzILlYadlKZI7ajS2NuOqi5QEA74PVRDiGxAaF6qc1QI3mEuj2FYB+RFMK5K5K
hmMvGg0=
=wjO3
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Karl Skomski <k.skomski@famedly.com>"]
sign_commit = true
sign_tag = true
sign_archive = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 8CE8 7D0A 71A4 33ED 5EF6  0530 10AA 5938 CACF 94D9
Comment: Karl Skomski <k.skomski@famedly.com>

xjMEZLZxqxYJKwYBBAHaRw8BAQdARff2wUsInmpQDZc5MuR7WCdLykzoWx+6II80
587zTDPCwBEEHxYKAIMFgmS2casFiQPCZwADCwkHCRAQqlk4ys+U2UcUAAAAAAAe
ACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmfhvFNUnHpk3i3mW3Wv05fX
S21aFCM4xHuusypeSHq8BwMVCggCmwECHgEWIQSM6H0KcaQz7V72BTAQqlk4ys+U
2QAAau4BAKpJjZsIkFs3dQvgYZZS4oY1rHp6SRaQ0CqFApWSId0BAP4k/JTPwUws
Vo8excbjUSuq7AliHdOhzyIK9Il6r9GSAc0kS2FybCBTa29tc2tpIDxrLnNrb21z
a2lAZmFtZWRseS5jb20+wsAUBBMWCgCGBYJktnGrBYkDwmcAAwsJBwkQEKpZOMrP
lNlHFAAAAAAAHgAgc2FsdEBub3RhdGlvbnMuc2VxdW9pYS1wZ3Aub3JnrdimnkbE
SwroRmYRvPUoDq/aw2ynmiFt32huouoS7OsDFQoIApkBApsBAh4BFiEEjOh9CnGk
M+1e9gUwEKpZOMrPlNkAAGCXAQC55aeOD5wfsSrBYbT/o7UWHM86LtZ8XpGVKtgi
xpS5ZwD/XSQj59+UnrMPs0gmDdIEmqe2paJqy+KEAgL7ksp0zw3OMwRktnGrFgkr
BgEEAdpHDwEBB0D0kOv/LlVgCjbVUthRCDx71YgKJXJYjNv4OwgbgSgX3MLAxQQY
FgoBNwWCZLZxqwWJA8JnAAkQEKpZOMrPlNlHFAAAAAAAHgAgc2FsdEBub3RhdGlv
bnMuc2VxdW9pYS1wZ3Aub3JnGS6c16wBbAad+DrT+l89CKa44x+Ev2kLCXAjBZD9
Ou8CmwK+oAQZFgoAbwWCZLZxqwkQmxPF0w1CSo5HFAAAAAAAHgAgc2FsdEBub3Rh
dGlvbnMuc2VxdW9pYS1wZ3Aub3JngTvbL1Bih+qMgYIt6lf1bUQ0+VnidBPib6xx
rplVLNQWIQS8Goli9hBmc052qp6bE8XTDUJKjgAA56AA/190caB7Vri4XyssET0d
Kr2ToePshWiVYVI1IycmfIRrAP9SJO0zYApEEgO9rKqMk2xDtr6OIt51YLdtf1rN
NKTBAhYhBIzofQpxpDPtXvYFMBCqWTjKz5TZAADUrwEAsax+sALpvx50ZKMGoNVS
We8pmc+SXddQrsdIo4GhpJwBAKFX+ka6LXdutaloZaWPPDIVZDAq3O+uI2SRph9k
qO8A
=W2E8
-----END PGP PUBLIC KEY BLOCK-----
"""

[authorization."Paul Iov <p.iov@famedly.com>"]
sign_commit = true
sign_tag = true
sign_archive = true
add_user = true
retire_user = true
audit = true
keyring = """
-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: 1B9E A4C2 7D43 1B9E CBBC  F27A 2D76 C489 19B6 4673
Comment: Paul Iov <p.iov@famedly.com>

xjMEZO8ggxYJKwYBBAHaRw8BAQdA6LKIPGomyWBbY2kYlFfg6mMC51qaNvbXkpuG
eZvUuSzCwBEEHxYKAIMFgmTvIIMFiQPCZwADCwkHCRAtdsSJGbZGc0cUAAAAAAAe
ACBzYWx0QG5vdGF0aW9ucy5zZXF1b2lhLXBncC5vcmdYtqKmsqyWNz8bhdZf2sS8
khGn4o308mAjEw2A4JpcgwMVCggCmwECHgEWIQQbnqTCfUMbnsu88notdsSJGbZG
cwAAsbMA/1VtAiG2hH1jEKcZRKIJgkbGCXOfAeJvYqHaC1ZML1TnAP9SHPz6GZZM
kHZHs1SaEZ/tU4dlntchPKAK0MvjWF4uBc0cUGF1bCBJb3YgPHAuaW92QGZhbWVk
bHkuY29tPsLAFAQTFgoAhgWCZO8ggwWJA8JnAAMLCQcJEC12xIkZtkZzRxQAAAAA
AB4AIHNhbHRAbm90YXRpb25zLnNlcXVvaWEtcGdwLm9yZ+V7Pb7v0bfGQl8E0WnV
es6vcFvwgz897lO3okM5a5xIAxUKCAKZAQKbAQIeARYhBBuepMJ9Qxuey7zyei12
xIkZtkZzAACYGQD9GOrESsjr1O1yjzrL3hcde8Chqhhnp8zNVwDq1/WwZ7IA/22+
24nOdhGfv09qAk5ebxTcWOoCS/Ir7bS18O+giLkBzjMEZO8ggxYJKwYBBAHaRw8B
AQdAKgc2jLl4iUK0d4sPonzdhLIfQ/mVQm0zXNhz86vCBDfCwMUEGBYKATcFgmTv
IIMFiQPCZwAJEC12xIkZtkZzRxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNlcXVv
aWEtcGdwLm9yZ+GqNTEYkOqO0cLuZHKLlqiBLAGaWlUXz6ah3IWVoYUmApsCvqAE
GRYKAG8FgmTvIIMJEKegtHx9A/XHRxQAAAAAAB4AIHNhbHRAbm90YXRpb25zLnNl
cXVvaWEtcGdwLm9yZ54FKE7egO7aBGw7Nga8VdvLbt659Uwm7pPjfeYBHpGjFiEE
6yhAxJ6PMfIKR01qp6C0fH0D9ccAAF1gAP0VTC98WA2cE1ocyIgJp/EXC6hckfjU
zrDMQwXV72h0EAD/YpFWN9CauX8lJ4qfiki89SPbBFLSUPjEL17/Z9SAjAoWIQQb
nqTCfUMbnsu88notdsSJGbZGcwAADFUA/0c5Jw1af3Llz+Pvva3YkiI4cO1WySRE
0YO599sajCpOAP9DeCBsZiJiSts9e/vUFgbhjxYpBrtLzFtitxLce7fkCg==
=c0kU
-----END PGP PUBLIC KEY BLOCK-----
"""
