name: authenticate-commits
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  authenticate-commits:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      issues: write

    steps:
      - name: Authenticating commits
        uses: famedly/authenticate-commits@egraven/support-shadow-policies
        with:
          comment: on-error
          checkout_submodules: true
          policy_file: "openpgp-policy/openpgp.policy.toml"
          checkout_ssh_key: ${{ secrets.CI_SSH_PRIVATE_KEY }}